# Team: 39
# Chuxin Zou 1061714 China
# Dongnan Cao 970205 China
# Fuyao Zhang 813023 Austalia
# Liqin Zhang 890054 China
# Zhiqian Chen 1068712 Australia

# Author: Chuxin Zou (1061714)

# stop the system

- hosts: COMP90024
  tasks: 
    - name: stop the system
      command: kill -9 $(ps -ef | grep python | grep -v grep | awk '{print$2}')
