# Team: 39
# Chuxin Zou 1061714 China
# Dongnan Cao 970205 China
# Fuyao Zhang 813023 Austalia
# Liqin Zhang 890054 China
# Zhiqian Chen 1068712 Australia

# Author: Chuxin Zou (1061714)

- name: Download Code From Github Using Ansible.
  git:
    repo: 'https://github.com/MrDoghead/COMP90024_2020_Project_G39_City_Analytics_on_the_Cloud.git'
    dest: /home/ubuntu/project