# Team: 39
# Chuxin Zou 1061714 China
# Dongnan Cao 970205 China
# Fuyao Zhang 813023 Austalia
# Liqin Zhang 890054 China
# Zhiqian Chen 1068712 Australia

# Author: Chuxin Zou (1061714)

# create volumes from vars

- name: Create volume
  os_volume:
    display_name: '{{ item.vol_name }}'
    size: '{{ item.vol_size }}'
    availability_zone: '{{ availability_zone }}'
    wait: yes
    timeout: 600
    state: present
  loop: '{{ volumes }}'
  register: os_vol


# get a list of volume ids from the results of os_vol
- name: Create a list of volume IDs
  set_fact:
    os_vol_ids: '{{ os_vol_ids|default([]) + [item.id] }}'
  loop: '{{ os_vol.results }}'


- debug:
    msg: 'Volume {{ os_vol_ids }} have been created.'